version = 1
SPDX-PackageName = "SAP-docs/btp-master-data-integration"
SPDX-PackageSupplier = "Madeline Schaefer (madeline.schaefer@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/SAP-docs/btp-master-data-integration"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and SAP-docs/btp-master-data-integration contributors"
SPDX-License-Identifier = "CC-BY-4.0"
